/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".app-school-report[_ngcontent-%COMP%]    + .app-school-report[_ngcontent-%COMP%] {\r\n    margin-top: 15px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=schools-reports-list.component.css.shim.ngstyle.js.map