/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["[_nghost-%COMP%] {\r\n    position: fixed;\r\n    top: 0;\r\n    left: 0;\r\n    width: 100%;\r\n    height: 100%;\r\n    background-color: rgba(0,0,0, 0.15);\r\n    display: flex;\r\n    -ms-flex-direction: column;\r\n    -webkit-flex-direction: column;\r\n    flex-direction: column;\r\n    align-items: center;\r\n    justify-content: center;\r\n    z-index: 1050;\r\n    overflow: hidden;\r\n}\r\n\r\n.loading-viewer[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    -ms-flex-direction: column;\r\n    -webkit-flex-direction: column;\r\n    flex-direction: column;\r\n    align-items: center;\r\n}\r\n\r\n.caption-text[_ngcontent-%COMP%] {\r\n    padding: 10px 15px;\r\n    background-color: rgba(0,0,0,0.15);\r\n    color: white;\r\n    margin-top: 15px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=loading-view.component.css.shim.ngstyle.js.map