//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaResult
    {
        public int ProjectCode { get; set; }
        public string ParticipCode { get; set; }
        public int SubjectCode { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string DocumSer { get; set; }
        public string DocumNum { get; set; }
        public string SchoolId { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public int PrimaryMark { get; set; }
        public int Grade5 { get; set; }
        public Nullable<int> Grade100 { get; set; }
        public string Marks { get; set; }
        public string Parts { get; set; }
        public string Elements { get; set; }
        public string Skills { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual School School { get; set; }
    }
}
