//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectParticipEdit
    {
        public string ParticipCode { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string ClassNumbers { get; set; }
        public string SchoolId { get; set; }
        public Nullable<int> CategId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> NSubjectCode { get; set; }
    
        public virtual ProjectParticip ProjectParticip { get; set; }
    }
}
