//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportStatistic
    {
        public System.Guid Id { get; set; }
        public int ReportId { get; set; }
        public string UserName { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
