/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["[_nghost-%COMP%] {\r\n    margin: 10px 0;\r\n    display: flex;\r\n    -ms-align-content: flex-end;\r\n    -webkit-align-content: flex-end;\r\n    align-items: baseline;\r\n    flex-direction: row-reverse;\r\n}\r\n\r\n.page-navigator-arrow[_ngcontent-%COMP%]{\r\n    padding: 10px;\r\n    cursor: pointer;\r\n}\r\n\r\n#page-index[_ngcontent-%COMP%]{\r\n    \r\n    border-bottom: 1px solid black;\r\n    text-align: center;\r\n    padding: 5px 10px;\r\n}\r\n\r\n#page-size[_ngcontent-%COMP%]{\r\n    width: 50px;\r\n}\r\n\r\n.page-navigator[_ngcontent-%COMP%]{\r\n    margin-left: 15px;\r\n}\r\n\r\nlabel[_ngcontent-%COMP%]{\r\n    font-weight: normal;\r\n    font-size: small;\r\n    margin-right: 5px;\r\n}\r\n\r\n.mat-select[_ngcontent-%COMP%]{\r\n    text-align: center;\r\n}\r\n\r\n.disabled[_ngcontent-%COMP%]{\r\n    opacity: 0.3;\r\n    cursor: default;\r\n}"];
export { styles as styles };
//# sourceMappingURL=table-paginator.css.shim.ngstyle.js.map