/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".mat-form-field[_ngcontent-%COMP%]{\r\n    display: block;\r\n    width: 350px;\r\n}\r\n\r\n.class-select[_ngcontent-%COMP%]{\r\n    width: 130px;\r\n}\r\n\r\n.form-buttons[_ngcontent-%COMP%]{\r\n    margin-top:30px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=add-or-update.component.css.shim.ngstyle.js.map