/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".table-container[_ngcontent-%COMP%]{\r\n    margin: 15px 0;\r\n}\r\n\r\n.content-center[_ngcontent-%COMP%] {\r\n    height: 60vh;\r\n    display: flex;\r\n    justify-content: center;\r\n    align-items: center;\r\n    -ms-flex-direction: column;\r\n    -webkit-flex-direction: column;\r\n    flex-direction: column;\r\n}\r\n\r\n.pass-color[_ngcontent-%COMP%]{\r\n    color: green;\r\n}\r\n\r\n.fail-color[_ngcontent-%COMP%]{\r\n    color: red;\r\n}\r\n\r\n.no-participate-color[_ngcontent-%COMP%]{\r\n    color: orange;\r\n}\r\n\r\n.notActual[_ngcontent-%COMP%] {\r\n    background-color: lightgray;\r\n}"];
export { styles as styles };
//# sourceMappingURL=firing-list.component.css.shim.ngstyle.js.map