/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".mat-form-field[_ngcontent-%COMP%] {\r\n    display: block;\r\n    width: 350px;\r\n}\r\n\r\n.form-buttons[_ngcontent-%COMP%] {\r\n    margin-top: 30px;\r\n}\r\n\r\n.birthday-wrapper[_ngcontent-%COMP%] {\r\n    display: flex;\r\n}\r\n\r\n.birthday-wrapper[_ngcontent-%COMP%]    > .mat-form-field[_ngcontent-%COMP%] {\r\n    width: 250px;\r\n}\r\n\r\n.birthday-wrapper[_ngcontent-%COMP%]    > .mat-form-field[_ngcontent-%COMP%]    + .mat-form-field[_ngcontent-%COMP%] {\r\n    margin-left: 15px;\r\n}\r\n\r\n.birthday-wrapper[_ngcontent-%COMP%]    > .birthday-day[_ngcontent-%COMP%] {\r\n    width: 70px;\r\n}\r\n\r\n.birthday-wrapper[_ngcontent-%COMP%]    > .birthday-month[_ngcontent-%COMP%] {\r\n    width: 150px;\r\n}\r\n\r\n.birthday-wrapper[_ngcontent-%COMP%]    > .birthday-year[_ngcontent-%COMP%] {\r\n    width: 110px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=add-particip.component.css.shim.ngstyle.js.map