/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".example-container[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    flex-direction: column;\r\n    max-height: 500px;\r\n    min-width: 300px;\r\n}\r\n\r\n.mat-table[_ngcontent-%COMP%] {\r\n    overflow: auto;\r\n    max-height: 500px;\r\n}\r\n\r\n.mat-column-Year[_ngcontent-%COMP%]{\r\n    max-width: 130px;\r\n}\r\n\r\n.mat-column-Status[_ngcontent-%COMP%]{\r\n    max-width: 230px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=school-files.component.css.shim.ngstyle.js.map