/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".mat-subheader[_ngcontent-%COMP%] {\r\n    margin-top: 15px !important;\r\n}\r\n\r\n.mat-list[_ngcontent-%COMP%]{\r\n    padding-top: 0;\r\n}"];
export { styles as styles };
//# sourceMappingURL=home.component.css.shim.ngstyle.js.map