/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".mat-radio-group[_ngcontent-%COMP%]{\r\n    margin-bottom: 25px;\r\n    display: block;\r\n}\r\n\r\n.mat-radio-button[_ngcontent-%COMP%]    + mat-radio-button[_ngcontent-%COMP%]{\r\n    margin-left: 20px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=hire-particip.component.css.shim.ngstyle.js.map