/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".mat-column-index[_ngcontent-%COMP%]{\r\n    max-width: 50px;\r\n}\r\n\r\n.mat-column-DocumNumber[_ngcontent-%COMP%]{\r\n    max-width: 120px;\r\n}\r\n\r\n.mat-column-actions[_ngcontent-%COMP%]{\r\n    max-width: 295px;\r\n}\r\n\r\n.mat-column-Marks[_ngcontent-%COMP%]{\r\n    font-size: 9pt;\r\n}\r\n\r\n.search-field[_ngcontent-%COMP%] {\r\n    margin-top: 20px;\r\n}\r\n\r\n.table-container[_ngcontent-%COMP%]{\r\n    margin-top: 15px;\r\n}\r\n\r\n.red-row[_ngcontent-%COMP%] {\r\n    background-color: rgba(255,0,0,0.35)\r\n}\r\n\r\n.actions-container[_ngcontent-%COMP%]{\r\n    padding: 10px;\r\n}\r\n\r\n.filter-field[_ngcontent-%COMP%]{\r\n    width: 100%;\r\n    padding: 0 15px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=protocols.component.css.shim.ngstyle.js.map