/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".markInput[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    width: 25px;\r\n    padding: 1px;\r\n}\r\n\r\n.markLabel[_ngcontent-%COMP%] {\r\n    width: 40px;\r\n}\r\n\r\n.max-mark-wrapper[_ngcontent-%COMP%]{\r\n    display: inline-block;\r\n    position: relative;\r\n    border: 1px solid lightgray;\r\n    padding: 5px 8px;\r\n    margin-left: 10px;\r\n    background-color: #fbfafa;\r\n}\r\n\r\n.max-mark-wrapper[_ngcontent-%COMP%]::after {\r\n    content: \" \";\r\n    position: absolute;\r\n    top: 35%; \r\n    left: -5px;\r\n    margin-left: -5px;\r\n    border-width: 5px;\r\n    border-style: solid;\r\n    border-color: black transparent transparent transparent;\r\n    -moz-transform: rotate(90deg);\r\n    -ms-transform: rotate(90deg);\r\n    -o-transform: rotate(90deg);\r\n    -webkit-transform: rotate(90deg);\r\n    transform: rotate(90deg);\r\n}\r\n\r\n.option-number-wrapper[_ngcontent-%COMP%]{\r\n    font-size: 16pt;\r\n}\r\n\r\n.optionLabel[_ngcontent-%COMP%]{\r\n    width: auto;\r\n}"];
export { styles as styles };
//# sourceMappingURL=marks-protocol.component.css.shim.ngstyle.js.map