/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".example-container[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    flex-direction: column;\r\n    min-width: 300px;\r\n    margin-top: 40px;\r\n}\r\n\r\n.mat-table[_ngcontent-%COMP%] {\r\n    overflow: auto;\r\n    \r\n}\r\n\r\n.mat-column-Code[_ngcontent-%COMP%]{\r\n    max-width: 130px\r\n}\r\n\r\n.filter-field[_ngcontent-%COMP%] {\r\n    min-height: 64px;\r\n    padding: 8px 24px 0;\r\n    font-size: 14px;\r\n    flex: 1 1 auto;\r\n}\r\n\r\n.table-filters[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    align-items: baseline;\r\n    padding: 0 15px;\r\n}\r\n\r\n\r\n.mat-checkbox-layout[_ngcontent-%COMP%] {\r\n    font-weight: normal;\r\n}\r\n\r\n.newItem[_ngcontent-%COMP%] {\r\n    background-color: #90ee9078;\r\n}\r\n\r\n\r\n.content-center[_ngcontent-%COMP%] {\r\n    height: 60vh;\r\n    display: flex;\r\n    justify-content: center;\r\n    align-items: center;\r\n    -ms-flex-direction: column;\r\n    -webkit-flex-direction: column;\r\n    flex-direction: column;\r\n}"];
export { styles as styles };
//# sourceMappingURL=hiring-list.component.css.shim.ngstyle.js.map