/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["h2[_ngcontent-%COMP%]{\r\n    margin-bottom: 35px;\r\n}\r\n\r\nlabel[_ngcontent-%COMP%]{\r\n    display: block;\r\n    margin-bottom: 15px;\r\n}\r\n\r\n.mat-card[_ngcontent-%COMP%]    + mat-card[_ngcontent-%COMP%] {\r\n    margin-top: 25px;\r\n}\r\n\r\n.mat-radio-button[_ngcontent-%COMP%]    + .mat-radio-button[_ngcontent-%COMP%] {\r\n    margin-left: 15px;\r\n}\r\n\r\n.content-center[_ngcontent-%COMP%] {\r\n    height: 60vh;\r\n    display: flex;\r\n    justify-content: center;\r\n    align-items: center;\r\n    -ms-flex-direction: column;\r\n    -webkit-flex-direction: column;\r\n    flex-direction: column;\r\n}"];
export { styles as styles };
//# sourceMappingURL=profile.component.css.shim.ngstyle.js.map