/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".school-select[_ngcontent-%COMP%]{\r\n    width: 250px;\r\n}\r\n\r\n.mat-form-field[_ngcontent-%COMP%]    + .mat-form-field[_ngcontent-%COMP%]{\r\n    margin-left: 15px;\r\n}\r\n\r\n.results[_ngcontent-%COMP%]{\r\n    margin-top: 25px;\r\n}\r\n\r\n.particip-card[_ngcontent-%COMP%] {\r\n    border: 1px solid lightgray;\r\n    padding: 15px;\r\n}\r\n\r\n.particip-card[_ngcontent-%COMP%]    + .particip-card[_ngcontent-%COMP%]{\r\n    margin-top: 10px;\r\n    \r\n}\r\n\r\n.card-wrapper[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    -webkit-justify-content: space-between;\r\n    justify-content: space-between;\r\n    -webkit-align-items: center;\r\n    align-content: center;\r\n    font-size: 10pt;\r\n}\r\n\r\n.particip-info[_ngcontent-%COMP%]{\r\n\r\n}\r\n\r\n.search-field[_ngcontent-%COMP%]{\r\n    width: 250px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=transfer-particip.component.css.shim.ngstyle.js.map