/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".mat-column--id[_ngcontent-%COMP%] {\r\n    max-width: 60px;\r\n}\r\n\r\n.mat-column-upd-action[_ngcontent-%COMP%], .mat-column-del-action[_ngcontent-%COMP%] {\r\n    max-width: 60px;\r\n    text-align: center;\r\n}\r\n\r\n.mat-column-DocumNumber[_ngcontent-%COMP%] {\r\n    max-width: 155px;\r\n}\r\n\r\n.mat-column-ClassName[_ngcontent-%COMP%] {\r\n    max-width: 100px;\r\n}\r\n\r\n.actions-container[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    flex-direction: row;\r\n    justify-content: space-between;\r\n    align-items: baseline;\r\n    padding: 10px;\r\n}\r\n\r\n.filter-field[_ngcontent-%COMP%] {\r\n    flex: 1 1 auto;\r\n    padding: 10px 15px;\r\n}\r\n\r\nh2[_ngcontent-%COMP%] {\r\n    margin-bottom: 25px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=list.component.css.shim.ngstyle.js.map