/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".alert[_ngcontent-%COMP%]{\r\n    margin-bottom:0;\r\n}"];
export { styles as styles };
//# sourceMappingURL=home.component.css.shim.ngstyle.js.map