/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".table-actions[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    justify-content: space-between;\r\n    align-items: baseline;\r\n    margin-top: 20px;\r\n}\r\n\r\nth[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n}\r\n\r\n.red-cell[_ngcontent-%COMP%] {\r\n    background-color: #f44336;\r\n}\r\n\r\n.mat-form-field[_ngcontent-%COMP%]    + .mat-form-field[_ngcontent-%COMP%]{\r\n    margin-left: 15px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=protocols-list.component.css.shim.ngstyle.js.map