//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cokoContext : DbContext
    {
        public cokoContext()
            : base("name=cokoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<Collector> Collectors { get; set; }
        public virtual DbSet<CollectorSchool> CollectorSchools { get; set; }
        public virtual DbSet<idoege2016_res> idoege2016_res { get; set; }
        public virtual DbSet<readyoneclass_res> readyoneclass_res { get; set; }
        public virtual DbSet<towntype> towntypes { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportStatistic> ReportStatistics { get; set; }
        public virtual DbSet<oge_16_res> oge_16_res { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
    }
}
