//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cokoContext : DbContext
    {
        public cokoContext()
            : base("name=cokoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Collector> Collectors { get; set; }
        public virtual DbSet<CollectorSchool> CollectorSchools { get; set; }
        public virtual DbSet<Monit95users> Monit95users { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportStatistic> ReportStatistics { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<TownType> TownTypes { get; set; }
        public virtual DbSet<oge_16_res> oge_16_res { get; set; }
        public virtual DbSet<TestElement> TestElements { get; set; }
        public virtual DbSet<ExerElement> ExerElements { get; set; }
        public virtual DbSet<ExerMark> ExerMarks { get; set; }
        public virtual DbSet<NsurSubject> NsurSubjects { get; set; }
        public virtual DbSet<ParticipTest> ParticipTests { get; set; }
        public virtual DbSet<ProjectParticip> ProjectParticips { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectTest> ProjectTests { get; set; }
        public virtual DbSet<TestExercis> TestExercises { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
    }
}
