//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectorSchool
    {
        public int CollectorId { get; set; }
        public string SchoolId { get; set; }
        public short StatusCode { get; set; }
    
        public virtual Collector Collector { get; set; }
        public virtual School School { get; set; }
    }
}
