//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerMark
    {
        public int ProjectCode { get; set; }
        public System.Guid TestId { get; set; }
        public int TestNumber { get; set; }
        public System.DateTime TestDate { get; set; }
        public string ParticipCode { get; set; }
        public int ExerNumber { get; set; }
        public int Mark { get; set; }
    
        public virtual ParticipTest ParticipTest { get; set; }
        public virtual TestExercis TestExercis { get; set; }
    }
}
