//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerElement
    {
        public System.Guid TestId { get; set; }
        public int ExerNumber { get; set; }
        public string ElementCode { get; set; }
    
        public virtual TestElement TestElement { get; set; }
        public virtual TestExercis TestExercis { get; set; }
    }
}
