//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class oge_16_res
    {
        public string ParticipId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string DocumSer { get; set; }
        public string DocumNum { get; set; }
        public string SchoolId { get; set; }
        public int SubjectCode { get; set; }
        public double PrimaryMark { get; set; }
        public double TestMark5 { get; set; }
        public string Marks { get; set; }
        public Nullable<double> t1 { get; set; }
        public Nullable<double> t2 { get; set; }
        public Nullable<double> t3 { get; set; }
        public Nullable<double> t4 { get; set; }
        public Nullable<double> t5 { get; set; }
        public Nullable<double> t6 { get; set; }
        public Nullable<double> t7 { get; set; }
        public Nullable<double> t8 { get; set; }
        public Nullable<double> t9 { get; set; }
        public Nullable<double> t10 { get; set; }
        public Nullable<double> t11 { get; set; }
        public Nullable<double> t12 { get; set; }
        public Nullable<double> t13 { get; set; }
        public Nullable<double> t14 { get; set; }
        public Nullable<double> t15 { get; set; }
        public Nullable<double> t16 { get; set; }
        public Nullable<double> t17 { get; set; }
        public Nullable<double> t18 { get; set; }
        public Nullable<double> t19 { get; set; }
        public Nullable<double> t20 { get; set; }
        public Nullable<double> t21 { get; set; }
        public Nullable<double> t22 { get; set; }
        public Nullable<double> t23 { get; set; }
        public Nullable<double> t24 { get; set; }
        public Nullable<double> t25 { get; set; }
        public Nullable<double> t26 { get; set; }
    
        public virtual School School { get; set; }
    }
}
