//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectCode { get; set; }
        public string ParticipCode { get; set; }
        public string SNS { get; set; }
        public int SubjectCode { get; set; }
        public string Marks { get; set; }
        public Nullable<int> PrimaryMark { get; set; }
        public Nullable<int> Mark5 { get; set; }
        public string Parts { get; set; }
        public string Elements { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
