//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentViewModel()
        {
            this.ExerciseMarks = new HashSet<ExerciseMark>();
        }
    
        public int Id { get; set; }
        public int ProjectCode { get; set; }
        public string ParticipCode { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string SchoolId { get; set; }
        public string ClassCode { get; set; }
    
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExerciseMark> ExerciseMarks { get; set; }
        public virtual StudentViewModel ProjectParticipsV21 { get; set; }
        public virtual StudentViewModel ProjectParticipsV22 { get; set; }
        public virtual School School { get; set; }
    }
}
