//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class readyoneclass_res
    {
        public System.Guid Code { get; set; }
        public int year { get; set; }
        public string SNS { get; set; }
        public string SchoolID { get; set; }
        public string ClassCode { get; set; }
        public int OldGroupCode { get; set; }
        public short WasOrWasntDOO { get; set; }
        public short WasOrWasnt { get; set; }
        public Nullable<short> TestResult5 { get; set; }
        public Nullable<double> PrimaryMark { get; set; }
        public Nullable<double> t1 { get; set; }
        public Nullable<double> t2 { get; set; }
        public Nullable<double> t3 { get; set; }
        public Nullable<double> t4 { get; set; }
        public Nullable<double> t5 { get; set; }
        public Nullable<short> HealthGroupCode { get; set; }
        public Nullable<short> WasOrWasntOO { get; set; }
        public string TeacherCode { get; set; }
    
        public virtual School School { get; set; }
    }
}
