//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School()
        {
            this.CollectorSchools = new HashSet<CollectorSchool>();
            this.idoege2016_res = new HashSet<idoege2016_res>();
            this.readyoneclass_res = new HashSet<readyoneclass_res>();
            this.oge_16_res = new HashSet<oge_16_res>();
        }
    
        public string Id { get; set; }
        public string VPRcode { get; set; }
        public Nullable<int> GIAcode { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Director { get; set; }
        public string Phone { get; set; }
        public string Admin { get; set; }
        public string AdminPhone { get; set; }
        public string Email { get; set; }
        public int AreaId { get; set; }
        public Nullable<int> TypeCode { get; set; }
        public Nullable<int> ViewCode { get; set; }
        public Nullable<int> TownTypeCode { get; set; }
        public Nullable<int> GoverCode { get; set; }
        public string ReportLink { get; set; }
        public Nullable<int> PropertyTypeCode { get; set; }
        public string Monit95Login { get; set; }
    
        public virtual area area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectorSchool> CollectorSchools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idoege2016_res> idoege2016_res { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<readyoneclass_res> readyoneclass_res { get; set; }
        public virtual towntype towntype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oge_16_res> oge_16_res { get; set; }
    }
}
