//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Domain.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int ProjectCode { get; set; }
        public string ParticipCode { get; set; }
        public System.Guid TestId { get; set; }
        public int TestNumber { get; set; }
        public System.DateTime TestDate { get; set; }
        public Nullable<double> PrimaryMark { get; set; }
        public Nullable<short> Mark5 { get; set; }
        public string Marks { get; set; }
        public string Parts { get; set; }
        public string Elements { get; set; }
    
        public virtual ProjectParticip ProjectParticip { get; set; }
    }
}
