/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".report-card[_ngcontent-%COMP%] {\r\n    width: 1200px;\r\n}\r\n\r\n.section-head[_ngcontent-%COMP%] {\r\n    background-color: cornflowerblue;\r\n    text-align: center;\r\n    height: 50px;\r\n    vertical-align: middle;\r\n    color: white;\r\n}\r\n\r\n.myhead[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    text-transform: uppercase;\r\n    background-color: rgb(22,54,92);\r\n    color: white;\r\n    height: 20px;\r\n    vertical-align: middle;\r\n}\r\n\r\n.card-caption[_ngcontent-%COMP%] {\r\n    font-family: 'Times New Roman', Times, serif;\r\n    padding: 0 20px;\r\n}\r\n\r\n.cell-center[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    vertical-align: middle;\r\n}\r\n\r\n.report-table[_ngcontent-%COMP%] {\r\n    width: 1160px;\r\n    border: 1px solid black;\r\n    margin: 25px 0;\r\n}\r\n\r\n.report-table[_ngcontent-%COMP%]   td[_ngcontent-%COMP%] {\r\n    padding: 7px;\r\n}\r\n\r\n.particip-info[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] {\r\n    clear: both;\r\n    margin: 15px 0;\r\n}\r\n\r\n.risk-group-cell[_ngcontent-%COMP%]{\r\n    background-color: red;\r\n    color: white;\r\n    text-transform: uppercase;\r\n\r\n}\r\n\r\n.w-15[_ngcontent-%COMP%]{\r\n    width: 15%;\r\n}"];
export { styles as styles };
//# sourceMappingURL=report.component.css.shim.ngstyle.js.map