/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["label[_ngcontent-%COMP%]{\r\n    width: 140px;\r\n}\r\n\r\nform[_ngcontent-%COMP%]{\r\n    margin: 15px 0;\r\n}\r\n\r\n.control-wrapper[_ngcontent-%COMP%] + .control-wrapper[_ngcontent-%COMP%]{\r\n    margin-top: 10px;\r\n}\r\n\r\n.form-control[_ngcontent-%COMP%]{\r\n    display: inline;\r\n    width: 70px;\r\n}\r\n\r\n.alert[_ngcontent-%COMP%]{\r\n    margin-bottom: 0;\r\n    min-width: 215px;\r\n    width: max-content;\r\n}"];
export { styles as styles };
//# sourceMappingURL=protocol.component.css.shim.ngstyle.js.map