/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".conflict-text[_ngcontent-%COMP%] {\r\n    position: relative;\r\n}\r\n\r\n.fa[_ngcontent-%COMP%] {\r\n    position: absolute;\r\n    top: 10px;\r\n    right: 10px;\r\n    cursor: pointer;\r\n}\r\n\r\n.form-alert[_ngcontent-%COMP%] {\r\n    \r\n    display: inline-block;\r\n    margin-bottom: 0;\r\n}"];
export { styles as styles };
//# sourceMappingURL=add.component.css.shim.ngstyle.js.map