/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".bar-container[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    height: 15px;\r\n}\r\n\r\n.bar[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    font-size: 9pt;\r\n}\r\n\r\n.legend-container[_ngcontent-%COMP%] {\r\n    display:flex;\r\n    justify-content: flex-end;\r\n    margin-bottom: 7px;\r\n}\r\n\r\n.legend-wrapper[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    align-items: center;\r\n}\r\n\r\n.legend-color[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n    height: 15px;\r\n    width: 15px;\r\n    margin-right: 5px;\r\n}\r\n\r\n.legend-wrapper[_ngcontent-%COMP%]    + .legend-wrapper[_ngcontent-%COMP%] {\r\n    margin-left: 20px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=stacked-bar.component.css.shim.ngstyle.js.map