/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".upload-area[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    -webkit-justify-content: space-between;\r\n    justify-content: space-between;\r\n    -webkit-align-items: center;\r\n    align-items: center;\r\n    padding: 15px 20px;\r\n}\r\n\r\ninput[type=file][_ngcontent-%COMP%] {\r\n    display: none;\r\n}\r\n\r\n.alert[_ngcontent-%COMP%] {\r\n    margin-bottom: 0;\r\n}\r\n\r\n[_nghost-%COMP%]{\r\n    display: block;\r\n}\r\n\r\n.cancel-btn[_ngcontent-%COMP%] {\r\n    margin-left: 15px;\r\n}"];
export { styles as styles };
//# sourceMappingURL=uploader.component.css.shim.ngstyle.js.map