//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class area
    {
        public area()
        {
            this.schools = new HashSet<school>();
        }
    
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public string AreaFullName { get; set; }
        public string Административный_центр { get; set; }
    
        public virtual ICollection<school> schools { get; set; }
    }
}
