//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cokoEntitiesWAN : DbContext
    {
        public cokoEntitiesWAN()
            : base("name=cokoEntitiesWAN")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<ege_15_res_before> ege_15_res_before { get; set; }
        public virtual DbSet<ege_dat_sub> ege_dat_sub { get; set; }
        public virtual DbSet<ege_partcat> ege_partcat { get; set; }
        public virtual DbSet<oge_15_res> oge_15_res { get; set; }
        public virtual DbSet<oge_15_res_before> oge_15_res_before { get; set; }
        public virtual DbSet<school> schools { get; set; }
        public virtual DbSet<schooltype> schooltypes { get; set; }
        public virtual DbSet<towntype> towntypes { get; set; }
    }
}
