//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ege_dat_sub
    {
        public ege_dat_sub()
        {
            this.ege_15_res_before = new HashSet<ege_15_res_before>();
            this.oge_15_res_before = new HashSet<oge_15_res_before>();
            this.oge_15_res = new HashSet<oge_15_res>();
        }
    
        public int SubjectCode { get; set; }
        public string LetterCode { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> MarkBorder2014 { get; set; }
        public Nullable<int> MarkBorder2015 { get; set; }
        public Nullable<double> GpaRussia2014 { get; set; }
        public Nullable<double> GpaRussia2015 { get; set; }
        public Nullable<double> ForAtestat2015 { get; set; }
    
        public virtual ICollection<ege_15_res_before> ege_15_res_before { get; set; }
        public virtual ICollection<oge_15_res_before> oge_15_res_before { get; set; }
        public virtual ICollection<oge_15_res> oge_15_res { get; set; }
    }
}
