//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ege_partcat
    {
        public ege_partcat()
        {
            this.ege_15_res_before = new HashSet<ege_15_res_before>();
        }
    
        public int PartCategoryCode { get; set; }
        public string PartCategoryName { get; set; }
    
        public virtual ICollection<ege_15_res_before> ege_15_res_before { get; set; }
    }
}
