//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monit95App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class towntype
    {
        public int TownTypeCode { get; set; }
        public string TownTypeName { get; set; }
    }
}
