/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".school-table-width[_ngcontent-%COMP%]{\r\n    width: 450px !important;\r\n}\r\n\r\nth[_ngcontent-%COMP%]{\r\n    text-align:center;\r\n}\r\n\r\ntd[_ngcontent-%COMP%], th[_ngcontent-%COMP%]{\r\n    vertical-align: middle;\r\n}\r\n\r\n.number-column-width[_ngcontent-%COMP%]{\r\n    width: 70px;\r\n    text-align: center;\r\n}\r\n\r\n.glyphicon[_ngcontent-%COMP%]{\r\n    z-index: 100;\r\n}\r\n\r\ntable[_ngcontent-%COMP%]{\r\n    max-width: 100%;\r\n}"];
export { styles as styles };
//# sourceMappingURL=seminar-report-list.component.css.shim.ngstyle.js.map