/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".green-text[_ngcontent-%COMP%] {\r\n    color: green;\r\n}\r\n\r\n.mat-form-field[_ngcontent-%COMP%] {\r\n    flex: 1 1 auto;\r\n}\r\n\r\n.mat-column-select[_ngcontent-%COMP%], .mat-column-num[_ngcontent-%COMP%] {\r\n    max-width: 70px;\r\n}\r\n\r\n.mat-row[_ngcontent-%COMP%]:hover{\r\n    cursor:pointer;\r\n    background-color: #eee;\r\n}\r\n\r\n.lightgreen-back[_ngcontent-%COMP%] {\r\n    background-color: #e1ffe1;\r\n}\r\n\r\n.table-actions[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    justify-content: space-between;\r\n    align-items: baseline;\r\n    margin-top: 50px;\r\n}\r\n\r\n.table-actions[_ngcontent-%COMP%]    > .mat-form-field[_ngcontent-%COMP%] {\r\n    margin-right: 20px;\r\n}\r\n\r\n\r\n.center-block[_ngcontent-%COMP%] {\r\n    height: 60vh;\r\n    display: flex;\r\n    justify-content: center;\r\n    align-items: center;\r\n    -ms-flex-direction: column;\r\n    -webkit-flex-direction: column;\r\n    flex-direction: column;\r\n}"];
export { styles as styles };
//# sourceMappingURL=particips-list.component.css.shim.ngstyle.js.map